services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:$DB_PORT
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 5000:$PORT
    develop:
      watch:
        - action: sync
          path: .
          target: /app

volumes:
  db:
