services:
  redis:
    image: redis:alpine
    restart: always

  app:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      - PORT=8000
    ports:
      - "8000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
